# Generated by Django 5.1.4 on 2025-01-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CryptoPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cryptocurrency_pair", models.CharField(max_length=50)),
                ("prediction_date", models.DateField()),
                ("predicted_price_change", models.FloatField()),
                (
                    "probability_increase",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "probability_decrease",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "unique_together": {("cryptocurrency_pair", "prediction_date")},
            },
        ),
        migrations.CreateModel(
            name="MarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cryptocurrency", models.CharField(max_length=50)),
                ("date", models.DateTimeField()),
                ("open_price", models.FloatField()),
                ("high_price", models.FloatField()),
                ("low_price", models.FloatField()),
                ("close_price", models.FloatField()),
                ("volume", models.FloatField()),
                ("exchange", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "unique_together": {("cryptocurrency", "date", "exchange")},
            },
        ),
    ]
