# Generated by Django 5.1.4 on 2025-01-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("url", models.URLField()),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("POSITIVE", "Positive"),
                            ("NEGATIVE", "Negative"),
                            ("NEUTRAL", "Neutral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("polarity", models.FloatField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=200, null=True)),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="IndicatorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cryptocurrency", models.CharField(max_length=50)),
                ("date", models.DateTimeField()),
                ("indicator_name", models.CharField(max_length=100)),
                ("value", models.FloatField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["cryptocurrency", "date"],
                        name="crypto_anal_cryptoc_5990bd_idx",
                    ),
                    models.Index(
                        fields=["cryptocurrency", "indicator_name"],
                        name="crypto_anal_cryptoc_3c6fd5_idx",
                    ),
                    models.Index(
                        fields=["date", "indicator_name"],
                        name="crypto_anal_date_03e302_idx",
                    ),
                ],
                "unique_together": {("cryptocurrency", "date", "indicator_name")},
            },
        ),
        migrations.CreateModel(
            name="LongTermCryptoPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cryptocurrency_pair", models.CharField(db_index=True, max_length=50)),
                ("prediction_date", models.DateField(db_index=True)),
                ("predicted_price_change", models.FloatField()),
                ("predicted_close", models.FloatField()),
                ("model_type", models.CharField(max_length=50)),
                ("confidence_level", models.FloatField(default=1.0)),
            ],
            options={
                "unique_together": {
                    ("cryptocurrency_pair", "prediction_date", "model_type")
                },
            },
        ),
        migrations.CreateModel(
            name="MarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cryptocurrency", models.CharField(max_length=50)),
                ("date", models.DateTimeField()),
                ("open_price", models.FloatField()),
                ("high_price", models.FloatField()),
                ("low_price", models.FloatField()),
                ("close_price", models.FloatField()),
                ("volume", models.FloatField()),
                ("exchange", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "unique_together": {("cryptocurrency", "date", "exchange")},
            },
        ),
        migrations.CreateModel(
            name="ShortTermCryptoPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cryptocurrency_pair", models.CharField(db_index=True, max_length=50)),
                ("prediction_date", models.DateField(db_index=True)),
                ("predicted_price_change", models.FloatField()),
                ("predicted_close", models.FloatField()),
                ("current_price", models.FloatField()),
                ("model_type", models.CharField(max_length=50)),
                ("confidence_level", models.FloatField(default=1.0)),
            ],
            options={
                "unique_together": {
                    ("cryptocurrency_pair", "prediction_date", "model_type")
                },
            },
        ),
    ]
