# Generated by Django 5.1.4 on 2025-01-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PreprocessedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("close_price", models.FloatField()),
                ("high_price", models.FloatField()),
                ("low_price", models.FloatField()),
                ("cryptocurrency", models.CharField(max_length=100)),
                ("period", models.CharField(max_length=50)),
                ("price_change_24h", models.FloatField(blank=True, null=True)),
                ("SMA_30", models.FloatField(blank=True, null=True)),
                ("volatility_30", models.FloatField(blank=True, null=True)),
                ("SMA_90", models.FloatField(blank=True, null=True)),
                ("volatility_90", models.FloatField(blank=True, null=True)),
                ("SMA_180", models.FloatField(blank=True, null=True)),
                ("volatility_180", models.FloatField(blank=True, null=True)),
                ("SMA_365", models.FloatField(blank=True, null=True)),
                ("volatility_365", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TechAnalysed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("cryptocurrency", models.CharField(max_length=100)),
                ("period", models.CharField(max_length=50)),
                ("close_price", models.FloatField()),
                ("high_price", models.FloatField()),
                ("low_price", models.FloatField()),
                ("price_change_24h", models.FloatField(blank=True, null=True)),
                ("SMA_30", models.FloatField(blank=True, null=True)),
                ("volatility_30", models.FloatField(blank=True, null=True)),
                ("SMA_90", models.FloatField(blank=True, null=True)),
                ("volatility_90", models.FloatField(blank=True, null=True)),
                ("SMA_180", models.FloatField(blank=True, null=True)),
                ("volatility_180", models.FloatField(blank=True, null=True)),
                ("predicted_signal", models.IntegerField(blank=True, null=True)),
                ("target", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LongTermCryptoPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cryptocurrency_pair", models.CharField(db_index=True, max_length=50)),
                ("prediction_date", models.DateField(db_index=True)),
                ("predicted_price_change", models.FloatField()),
                ("predicted_close", models.FloatField()),
                ("model_type", models.CharField(max_length=50)),
                ("confidence_level", models.FloatField(default=1.0)),
            ],
            options={
                "unique_together": {
                    ("cryptocurrency_pair", "prediction_date", "model_type")
                },
            },
        ),
        migrations.CreateModel(
            name="MarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cryptocurrency", models.CharField(max_length=50)),
                ("date", models.DateTimeField()),
                ("open_price", models.FloatField()),
                ("high_price", models.FloatField()),
                ("low_price", models.FloatField()),
                ("close_price", models.FloatField()),
                ("volume", models.FloatField()),
                ("exchange", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "unique_together": {("cryptocurrency", "date", "exchange")},
            },
        ),
        migrations.CreateModel(
            name="ShortTermCryptoPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cryptocurrency_pair", models.CharField(db_index=True, max_length=50)),
                ("prediction_date", models.DateField(db_index=True)),
                ("predicted_price_change", models.FloatField()),
                ("predicted_close", models.FloatField()),
                ("model_type", models.CharField(max_length=50)),
                ("confidence_level", models.FloatField(default=1.0)),
            ],
            options={
                "unique_together": {
                    ("cryptocurrency_pair", "prediction_date", "model_type")
                },
            },
        ),
    ]
