# Generated by Django 5.1.4 on 2025-01-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("url", models.URLField()),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("POSITIVE", "Positive"),
                            ("NEGATIVE", "Negative"),
                            ("NEUTRAL", "Neutral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("polarity", models.FloatField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=200, null=True)),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
