# Generated by Django 5.1.4 on 2025-02-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("current_price", models.FloatField(blank=True, null=True)),
                ("price_1h", models.FloatField(blank=True, null=True)),
                ("price_24h", models.FloatField(blank=True, null=True)),
                ("change_percent_1h", models.FloatField(blank=True, null=True)),
                ("change_percent_24h", models.FloatField(blank=True, null=True)),
                ("prediction_date", models.DateTimeField(auto_now_add=True)),
                ("confidence", models.FloatField(default=0.9)),
            ],
        ),
    ]
