# Generated by Django 5.1.4 on 2025-01-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_analysis", "0002_marketdata_exchange"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="marketdata",
            unique_together={("cryptocurrency", "date", "exchange")},
        ),
    ]
